// app/api/v1/articles/[id]/route.ts

import { supabase } from '@/libs/supabase'
import { NextResponse } from 'next/server'
import { Article, ImageMetadata } from '@/types/articles'

// APIレスポンスをArticle型に変換する関数
function transformToArticle(rawData: any): Article {
  const metadata = rawData.metadata || {};
  const images: ImageMetadata[] = metadata.images || [];
  
  return {
    id: rawData.article_id,
    title: rawData.base_title,
    description: rawData.base_text?.substring(0, 100) + "...",
    imageUrl: images[0]?.url || "/images/image.png",
    author: metadata.authors?.[0] || "generated by Pattto",
    createdAt: rawData.created_at,
    content: rawData.base_text, // 完全な本文
    metadata: {
      images: images.map(img => ({
        url: img.url,
        alt: img.alt,
        type: img.type,
        credit: img.credit,
        caption: img.caption
      })),
      authors: metadata.authors || []
    }
  };
}

export async function GET(
  request: Request, 
  { params }: { params: { id: string } }
) {
  try {
    const { id } = params;

    const { data, error } = await supabase
      .from('articles')
      .select('*')
      .eq('article_id', id)
      .single();

    if (error) {
      console.error('Supabase error:', error);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    if (!data) {
      return NextResponse.json(
        { error: 'Article not found' }, 
        { status: 404 }
      );
    }
    console.log('##data / api/v1/articles/[id]:', data);

    const article = transformToArticle(data);
    
    // デバッグ用
    console.log('Raw metadata:', data.metadata);
    console.log('Transformed article metadata:', article.metadata);

    return NextResponse.json({ data: article }, { status: 200 });
  } catch (error) {
    console.error('Server error:', error);
    return NextResponse.json(
      { error: 'Internal Server Error' },
      { status: 500 }
    );
  }
}